// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8p066J9tGsq38Pv-l8krznmsWTjlTfo',
    appId: '1:751221114209:web:830fed2045a8fdf3bbb120',
    messagingSenderId: '751221114209',
    projectId: 'flutternotes-86293',
    authDomain: 'flutternotes-86293.firebaseapp.com',
    storageBucket: 'flutternotes-86293.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm8WKt3fZvtvZFKEFHz62qgq4cKexDHP0',
    appId: '1:751221114209:android:a38e0b4a14f74d0fbbb120',
    messagingSenderId: '751221114209',
    projectId: 'flutternotes-86293',
    storageBucket: 'flutternotes-86293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-kYNriazUArFG1LojCZ40Oq5u9zp3AM',
    appId: '1:751221114209:ios:76607bb15d2d4d98bbb120',
    messagingSenderId: '751221114209',
    projectId: 'flutternotes-86293',
    storageBucket: 'flutternotes-86293.appspot.com',
    iosClientId: '751221114209-pq09llefih1dmtq7usna2jutga5pvtm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv-kYNriazUArFG1LojCZ40Oq5u9zp3AM',
    appId: '1:751221114209:ios:76607bb15d2d4d98bbb120',
    messagingSenderId: '751221114209',
    projectId: 'flutternotes-86293',
    storageBucket: 'flutternotes-86293.appspot.com',
    iosClientId: '751221114209-pq09llefih1dmtq7usna2jutga5pvtm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
